apiVersion: apps/v1
kind: Deployment
metadata:
  name: fishsearcher-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fishsearcher
  template:
    metadata:
      labels:
        app: fishsearcher
    spec:
      containers:
      - name: fishsearcher
        image: yourdockerhubusername/fishsearcher:latest
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
